dt: 0.002

urdf_name: "g1_29_withsensor.urdf"
pinocchio_encoder_names:
  - left_hip_pitch_joint
  - left_hip_roll_joint
  - left_hip_yaw_joint
  - left_knee_joint
  - left_ankle_pitch_joint
  - left_ankle_roll_joint
  - right_hip_pitch_joint
  - right_hip_roll_joint
  - right_hip_yaw_joint
  - right_knee_joint
  - right_ankle_pitch_joint
  - right_ankle_roll_joint  

passive_encoder_names:


locked_encoder_names:
  - waist_yaw_joint
  - waist_roll_joint
  - waist_pitch_joint
  - left_shoulder_pitch_joint
  - left_shoulder_roll_joint
  - left_shoulder_yaw_joint
  - left_elbow_joint
  - left_wrist_roll_joint
  - left_wrist_pitch_joint
  - left_wrist_yaw_joint
  - right_shoulder_pitch_joint
  - right_shoulder_roll_joint
  - right_shoulder_yaw_joint
  - right_elbow_joint
  - right_wrist_roll_joint
  - right_wrist_pitch_joint
  - right_wrist_yaw_joint

all_encoder_names:
  - left_hip_pitch_joint
  - left_hip_roll_joint
  - left_hip_yaw_joint
  - left_knee_joint
  - left_ankle_pitch_joint
  - left_ankle_roll_joint
  - right_hip_pitch_joint
  - right_hip_roll_joint
  - right_hip_yaw_joint
  - right_knee_joint
  - right_ankle_pitch_joint
  - right_ankle_roll_joint  
  - waist_yaw_joint
  - waist_roll_joint
  - waist_pitch_joint
  - left_shoulder_pitch_joint
  - left_shoulder_roll_joint
  - left_shoulder_yaw_joint
  - left_elbow_joint
  - left_wrist_roll_joint
  - left_wrist_pitch_joint
  - left_wrist_yaw_joint
  - right_shoulder_pitch_joint
  - right_shoulder_roll_joint
  - right_shoulder_yaw_joint
  - right_elbow_joint
  - right_wrist_roll_joint
  - right_wrist_pitch_joint
  - right_wrist_yaw_joint

contact_kf:
  base_process_std: 0.1
  foothold_std: 0.05
  encoder_std: 0.01
  acceleration_bias_std: 0.25
  init_position_std: 0.01
  init_velocity_std: 0.1
  init_acc_bias_std: 0.1
  init_foothold_std: 0.025
  contact_classifier:
    lowpass_dt_cutoff: 0.005
    linear_lb: 80.0
    linear_ub: 110.0



Kp_locked_joints: [100, 50, 50, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100]
Kd_locked_joints: [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1 , 1,  1]


qdes_locked_joints: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

safe_loco_q_bounds:
  lower: [-1.0, -0.5, -0.5,  0.2, -1.0, -0.3, -1.0, -0.5, -0.5,  0.2, -1.0, -0.3]
  upper: [ 0.0,  0.5,  0.5,  1.8,  1.0,  0.3,  0.0,  0.5,  0.5,  1.8,  1.0,  0.3]

default_loco_q: [-0.25, 0, 0, 0.5, 0.25, 0, -0.25, 0, 0, 0.5, 0.25, 0]