# qp, id, posik
controller: "qp"

# mlip_flat, dcm, hlip, alip
ro_planner: "alip"

pose_command: 
  dt_lowpass: 0.0005
  velX_dt_cutoff: 0.01
  velY_dt_cutoff: 0.01
  vx_offset: 0.0
  vy_offset: 0.0
  TSS: 0.3
  TDS: 0.0
  znom: 0.75
  zsw_max: 0.2
  zsw_neg: -0.01 #-0.01
  stepWidthNominal: 0.3
  bezierSwingHorizontal: [0, 0, 1, 1, 1]
  bezierComVertical: [0, 0, 0, 1, 1, 1]
  maxStepSize: 1.0
  velXmax: 1.0
  velYmax: 0.5


friction:  
  frictionCoef: 1
  Lfront: 0.08
  Lback: 0.08
  W: 0
  Fz_lb: 100.
  Rot_frictionCoef: 0.046

  


qp:
  ifprintQP: false
  #zCOM stHipYaw basePitch baseRoll swx swy swz swHipYaw SwPitch 
  OutputKP: [150, 200, 600,500, 300, 300,300, 200,200]
  OutputKD: [2,5,8,8,3,3,3,5,3]



id:
  threshold: 0.000001
  OutputKP: [150, 200, 600,500, 500, 300,300, 200,200]
  OutputKD: [2,5,8,8,3,3,3,5,3]



posik:
  tol: 0.0001
  max_iter: 1000
  # hipRoll hipYaw hipPitch kneePitch toePitch
  JointKP: [1700, 450, 1200, 800, 250]
  JointKD: [25,    10,   20, 10, 1]



