# qp, id, posik
controller: "qp"

# mlip_flat, dcm, hlip, alip
ro_planner: "dcm"

pose_command: 
  dt_lowpass: 0.0005
  velX_dt_cutoff: 2
  velY_dt_cutoff: 2
  vx_offset: 0.0
  vy_offset: 0.0
  TSS: 0.3
  TDS: 0.05
  znom: 0.75
  zsw_max: 0.2
  zsw_neg: -0.01 #-0.01
  stepWidthNominal: 0.3
  bezierSwingHorizontal: [0, 0, 1, 1, 1]
  bezierComVertical: [0, 0, 0, 1, 1, 1]
  maxStepSize: 1.0
  velXmax: 1
  velYmax: 0.5


friction:  
  frictionCoef: 1
  Lfront: 0.08 #max 0.1
  Lback: -0.04 #max -0.06
  W: 0
  Fz_lb: 100.
  Rot_frictionCoef: 0.046

  


qp:
  ifprintQP: false
  #        zCOM stHipYaw basePitch baseRoll swx swy swz swHipYaw SwPitch 
  OutputW:  [1,    1,      1,        1,      3,  3,  1,   1, 1]
  OutputKP: [350,  200,    200,      200,   300, 300,200, 200,1000]
  OutputKD: [10,   10,     10,       10,     10, 10, 10,  10, 50]





id:
  threshold: 0.000001
  OutputKP: [150, 200, 600,500, 500, 300,300, 200,200]
  OutputKD: [2,5,8,8,3,3,3,5,3]



posik:
  tol: 0.0001
  max_iter: 1000
  # hipRoll hipYaw hipPitch kneePitch toePitch
  JointKP: [1700, 450, 1200, 800, 250]
  JointKD: [25,    10,   20, 10, 1]



