
controller: "posik"



pose_command: 
  dt_lowpass: 0.005
  yd_lowpass_dt_cutoff: [.5, .5, .5, .5, .5, .5, .5, .5, .5, .5]
  swingZ_lb: -0.9
  swingZ_ub: -0.4
  swingX_backward: -0.2
  swingX_forward: 0.2
  swingY_inner: 0.1
  swingY_outer: 0.2
  yaw_lb: -0.5
  yaw_ub: 0.5
  pitch_lb: -0.5
  pitch_ub: 0.5



qp:
  ifprintQP: true
  OutputKP: [ 300, 250, 300, 300, 1000,  300, 250, 300, 300, 1000]   
  OutputKD: [ 10,   5,   10,  5,    5,  10,   5,   10,    5,  5]

id:
  threshold: 0.000001
  OutputKP: [ 300, 250, 300, 300, 1000,  300, 250, 300, 300, 1000]  
  OutputKD: [ 10,   5,   10,  5,    5,  10,   5,   10,    5,  5]


velik:
  #for each leg
  JointKP: [100, 100, 100, 100, 100]
  #for each leg
  JointKD: [1, 1, 1, 1, 1]
  ik_gain: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

posik:
  tol: 0.0001
  max_iter: 1000
  JointKP: [100., 100., 100., 100., 100.]
  JointKD: [2,2,2,2,2]