
controller: "qp"



pose_command: 
  dt_lowpass: 0.0005
  yd_lowpass_dt_cutoff: [5, 2, 2, .5, .5, .5]
  stand2step_y_offset: 0.04
  x_offset: 0.0
  x_range: 0.05
  y_range: 0.05
  z_lb: 0.78
  z_ub: 0.88
  pitch_range: 0.1
  roll_range: 0.1
  yaw_range: 0.3


qp:
  ifprintQP: true
  OutputKP: [250, 250, 250, 250, 250, 250]
  # OutputKP: [550, 550, 550, 320, 1000, 320]  
  OutputKD: [5,5,5,5,5,5]

id:
  threshold: 0.000001
  OutputKP: [550, 550, 250, 250, 250, 250]
  OutputKD: [5,5,5,5,5,5]


velik:
  #for each leg
  JointKP: [150, 150, 150, 150, 150, 150]
  #for each leg
  JointKD: [3,3,3,3,3,3] 
  ik_gain: [1.5, 1, 1, 1, 1, 1]
  
friction:  
  frictionCoef: 1
  Lfront: 0.085
  Lback: 0.085
  W: 0.025
  Fz_lb: 100.
  Rot_frictionCoef: 0.046


posik:
  tol: 0.0001
  max_iter: 1000
  JointKP: [600. , 500., 500., 600., 500., 500.]
  JointKD: [20., 10., 20., 20., 10., 10.]
