dt: 0.0005

urdf_name: "h1_2.urdf"
pinocchio_encoder_names:
  - left_hip_yaw_joint
  - left_hip_pitch_joint
  - left_hip_roll_joint
  - left_knee_joint
  - left_ankle_pitch_joint
  - left_ankle_roll_joint
  - right_hip_yaw_joint
  - right_hip_pitch_joint
  - right_hip_roll_joint
  - right_knee_joint
  - right_ankle_pitch_joint
  - right_ankle_roll_joint


passive_encoder_names:


locked_encoder_names:
  - torso_joint
  - left_shoulder_pitch_joint
  - left_shoulder_roll_joint
  - left_shoulder_yaw_joint
  - left_elbow_pitch_joint
  - left_elbow_roll_joint
  - left_wrist_pitch_joint
  - left_wrist_yaw_joint
  - L_thumb_proximal_yaw_joint
  - L_thumb_proximal_pitch_joint
  - L_thumb_intermediate_joint  
  - L_thumb_distal_joint
  - L_index_proximal_joint
  - L_index_intermediate_joint
  - L_middle_proximal_joint
  - L_middle_intermediate_joint
  - L_ring_proximal_joint
  - L_ring_intermediate_joint
  - L_pinky_proximal_joint
  - L_pinky_intermediate_joint
  - right_shoulder_pitch_joint
  - right_shoulder_roll_joint 
  - right_shoulder_yaw_joint
  - right_elbow_pitch_joint
  - right_elbow_roll_joint
  - right_wrist_pitch_joint
  - right_wrist_yaw_joint
  - R_thumb_proximal_yaw_joint
  - R_thumb_proximal_pitch_joint
  - R_thumb_intermediate_joint
  - R_thumb_distal_joint
  - R_index_proximal_joint
  - R_index_intermediate_joint
  - R_middle_proximal_joint
  - R_middle_intermediate_joint
  - R_ring_proximal_joint
  - R_ring_intermediate_joint
  - R_pinky_proximal_joint
  - R_pinky_intermediate_joint

all_encoder_names:
  - left_hip_yaw_joint
  - left_hip_pitch_joint
  - left_hip_roll_joint
  - left_knee_joint
  - left_ankle_pitch_joint
  - left_ankle_roll_joint
  - right_hip_yaw_joint
  - right_hip_pitch_joint
  - right_hip_roll_joint
  - right_knee_joint
  - right_ankle_pitch_joint
  - right_ankle_roll_joint
  - torso_joint
  - left_shoulder_pitch_joint
  - left_shoulder_roll_joint
  - left_shoulder_yaw_joint
  - left_elbow_pitch_joint
  - left_elbow_roll_joint
  - left_wrist_pitch_joint
  - left_wrist_yaw_joint
  - L_thumb_proximal_yaw_joint
  - L_thumb_proximal_pitch_joint
  - L_thumb_intermediate_joint  
  - L_thumb_distal_joint
  - L_index_proximal_joint
  - L_index_intermediate_joint
  - L_middle_proximal_joint
  - L_middle_intermediate_joint
  - L_ring_proximal_joint
  - L_ring_intermediate_joint
  - L_pinky_proximal_joint
  - L_pinky_intermediate_joint
  - right_shoulder_pitch_joint
  - right_shoulder_roll_joint 
  - right_shoulder_yaw_joint
  - right_elbow_pitch_joint
  - right_elbow_roll_joint
  - right_wrist_pitch_joint
  - right_wrist_yaw_joint
  - R_thumb_proximal_yaw_joint
  - R_thumb_proximal_pitch_joint
  - R_thumb_intermediate_joint
  - R_thumb_distal_joint
  - R_index_proximal_joint
  - R_index_intermediate_joint
  - R_middle_proximal_joint
  - R_middle_intermediate_joint
  - R_ring_proximal_joint
  - R_ring_intermediate_joint
  - R_pinky_proximal_joint
  - R_pinky_intermediate_joint

contact_kf:
  base_process_std: 0.1
  foothold_std: 0.05
  encoder_std: 0.01
  acceleration_bias_std: 0.25
  init_position_std: 0.01
  init_velocity_std: 0.1
  init_acc_bias_std: 0.1
  init_foothold_std: 0.025
  contact_classifier:
    lowpass_dt_cutoff: 0.005
    linear_lb: 60.0
    linear_ub: 110.0
# Optional
Kp_locked_joints: [1000, 600, 1000, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700, 700]
Kd_locked_joints: [  15,  15,   15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15, 15]


#38 zeros
qdes_locked_joints: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
